// =============================================================
//  Baralho: Kipperkarten (Kipper Alemão)
//  Sistema alemão do século XIX, 36 cartas.
//  Foco em pessoas, dinâmicas interpessoais e situações concretas.
//  Sem inversão — leitura por contexto e direcionamento das figuras.
//  Para editar as cartas ou significados, mexa apenas neste arquivo.
// =============================================================

const kipper = {
    id: "kipper",
    nome: "Kipper",
    imagemPasta: "kipper",
    imagemExtensao: ".jpg",
    aceitaInversao: false,

    cartas: [
        "01 - Significador Masculino",
        "02 - Significadora Feminina",
        "03 - Estado do Casamento",
        "04 - Encontro",
        "05 - Homem Bom",
        "06 - Mulher Boa",
        "07 - Carta / Mensagem",
        "08 - Pessoa Falsa",
        "09 - Mudança",
        "10 - Viagem",
        "11 - Grande Ganho",
        "12 - Moça Rica",
        "13 - Rapaz Bom",
        "14 - Notícia Triste",
        "15 - Bom Desfecho",
        "16 - Seus Pensamentos",
        "17 - Receber um Presente",
        "18 - Criança Pequena",
        "19 - Fatalidade",
        "20 - Casa",
        "21 - Sala de Estar",
        "22 - Pessoa Fardada",
        "23 - Tribunal",
        "24 - Roubo",
        "25 - Altas Honras",
        "26 - Grande Fortuna",
        "27 - Dinheiro Inesperado",
        "28 - Expectativa",
        "29 - Prisão",
        "30 - Oficial do Tribunal",
        "31 - Doença Passageira",
        "32 - Tristeza e Desgosto",
        "33 - Pensamentos Sombrios",
        "34 - Trabalho",
        "35 - Longo Caminho",
        "36 - Grande Água / Esperança",
    ],

    significados: {
        "01 - Significador Masculino":  { significado: "O consulente, se homem. Representa a pessoa que faz a pergunta — seus interesses, sua posição na situação. Quando não é o consultante, indica homem jovem ou de meia-idade sem característica especial de destaque." },
        "02 - Significadora Feminina":  { significado: "A consulente, se mulher. Representa a pessoa que faz a pergunta — seus interesses, sua posição na situação. Quando não é a consultante, indica mulher jovem ou de meia-idade sem característica especial de destaque." },
        "03 - Estado do Casamento":     { significado: "União, vínculo, acordo, relação estabelecida. Pode ser casamento formal, parceria afetiva ou qualquer aliança importante entre duas pessoas. Indica conexão sólida — ou o estado atual dela." },
        "04 - Encontro":                { significado: "Reunião, contato social, camaradagem. Indica encontro físico ou virtual — pode ser planejado ou casual. As cartas ao redor revelam o tom do encontro." },
        "05 - Homem Bom":               { significado: "Homem mais velho, figura paterna, mentor, chefe. Homem de confiança — conselheiro, pai, sogro. Pode indicar também o 'outro homem' em contextos afetivos." },
        "06 - Mulher Boa":              { significado: "Mulher mais velha, figura materna, mentora. Mulher experiente e confiável — mãe, sogra, chefa. Pode indicar também a 'outra mulher' em contextos afetivos." },
        "07 - Carta / Mensagem":        { significado: "Notícia, informação, correspondência escrita. Comunicação chegando — e-mail, mensagem, documento, telefonema. O conteúdo depende das cartas ao redor." },
        "08 - Pessoa Falsa":            { significado: "Mentira, traição, engano, alguém que não é o que parece. Indica má-fé — pode ser uma pessoa específica ou uma situação que está sendo encoberta. Carta de alerta." },
        "09 - Mudança":                 { significado: "Transformação, transição, mudança de fase ou de lugar. Indica algo que se move — pode ser mudança de residência, de emprego, de relacionamento ou de perspectiva." },
        "10 - Viagem":                  { significado: "Deslocamento, viagem, movimento físico. Qualquer tipo de veículo ou trajeto. Indica distância — o que está longe ou o que se afasta." },
        "11 - Grande Ganho":            { significado: "Ganho financeiro expressivo, abundância, generosidade. Indica dinheiro em quantidade — herança, prêmio, lucro alto, retorno de investimento." },
        "12 - Moça Rica":               { significado: "Mulher jovem, estudante, pessoa charmosa ligada à beleza ou ao luxo. Pode indicar figura feminina jovem de destaque — namorada, filha, colega." },
        "13 - Rapaz Bom":               { significado: "Homem jovem, ambicioso, iniciante. Figura masculina jovem — namorado, filho, estagiário, colega novo. Ainda em formação, mas com potencial." },
        "14 - Notícia Triste":          { significado: "Decepção, tristeza, notícia ruim, emoção excessiva. Indica algo que magoa — pode ser informação negativa ou estado emocional de quem está no centro da questão." },
        "15 - Bom Desfecho":            { significado: "Resultado positivo, pequeno sucesso, amizade. Indica que algo se resolve bem — não é grande fortuna, mas é um desfecho favorável, uma vitória razoável." },
        "16 - Seus Pensamentos":        { significado: "Pensamentos, intenções, o que alguém está pensando sobre o consulente ou sobre a situação. Carta muito valiosa para perguntas sobre o que uma pessoa está sentindo ou planejando." },
        "17 - Receber um Presente":     { significado: "Presente, reconhecimento, visita, ajuda concreta. Algo que chega como gesto — pode ser material ou simbólico. Atenção e cuidado recebidos." },
        "18 - Criança Pequena":         { significado: "Criança real, inocência, ingenuidade, novo começo sem experiência. O que está no início — projeto nascente, relação nova, comportamento infantil." },
        "19 - Fatalidade":              { significado: "Fim, encerramento definitivo, má sorte, perda grave. Carta pesada — indica término real de algo, luto, resultado ruim. Nega cartas positivas próximas." },
        "20 - Casa":                    { significado: "Lar, família, propriedade, segurança doméstica. Indica estabilidade e raízes — o ambiente familiar ou o imóvel em questão. Carta de parada, de base." },
        "21 - Sala de Estar":           { significado: "Espaço privado, conforto, intimidade. O interior do lar — a vida cotidiana dentro de casa, o ambiente onde o consulente se sente à vontade. Pode indicar também o escritório pessoal." },
        "22 - Pessoa Fardada":          { significado: "Pessoa de uniforme — militar, policial, segurança, atleta. Indica disciplina, regras rígidas, burocracia. Pode representar o Estado ou qualquer estrutura de autoridade formal." },
        "23 - Tribunal":                { significado: "Instituição legal, grande empresa, corporação, prédio público. Indica processo judicial, negócio formal, ambiente institucional. O que é grande e impessoal." },
        "24 - Roubo":                   { significado: "Perda, roubo, desaparecimento, abandono. Algo foi tirado — pode ser objeto, pessoa, oportunidade ou energia. Indica subtração, não necessariamente criminosa." },
        "25 - Altas Honras":            { significado: "Reconhecimento, prêmio, fama, alta sociedade. Indica destaque positivo — promoção, elogio público, conquista de status. Carta muito favorável." },
        "26 - Grande Fortuna":          { significado: "Felicidade, realização, sonhos se tornando realidade. A melhor carta do baralho — indica abundância em todas as formas. Fortalece tudo ao redor." },
        "27 - Dinheiro Inesperado":     { significado: "Quantia pequena chegando de surpresa, retorno rápido, virada financeira pontual. Não é grande riqueza — é um alívio inesperado, um valor que aparece sem ser esperado." },
        "28 - Expectativa":             { significado: "Espera, esperança, anseio, paciência. Indica algo que ainda não chegou mas que o consulente aguarda com intensidade. O que está por vir — mas ainda não está aqui." },
        "29 - Prisão":                  { significado: "Limitação, bloqueio, situação que prende. Pode ser literal ou metafórica — contrato ruim, relacionamento sufocante, obrigação que não se pode largar." },
        "30 - Oficial do Tribunal":     { significado: "Advogado, juiz, figura de autoridade jurídica. Indica desacordo formal, processo, ambiguidade moral. Pessoa que decide — com poder, mas nem sempre com justiça." },
        "31 - Doença Passageira":       { significado: "Doença temporária, cansaço, problema de saúde breve. Indica baixa de energia ou adoecimento que passa. Pode indicar também cama — descanso, sono, intimidade sexual." },
        "32 - Tristeza e Desgosto":     { significado: "Sofrimento, angústia, estresse, desgosto profundo. Carta negativa — indica momento de dor emocional real. O que pesa e machuca." },
        "33 - Pensamentos Sombrios":    { significado: "Tristeza crônica, depressão, pensamentos negativos persistentes. Mais grave que a carta 32 — indica estado mental sombrio, ruminação, melancolia profunda." },
        "34 - Trabalho":                { significado: "Emprego, ocupação, tarefa, esforço. Indica atividade profissional ou qualquer trabalho concreto — pode ser árduo ou prazeroso, dependendo do contexto." },
        "35 - Longo Caminho":           { significado: "Grande distância, longo prazo, caminho extenso. Indica que algo vai demorar ou que a distância é real — física, temporal ou emocional. O que é longo e requer paciência." },
        "36 - Grande Água / Esperança": { significado: "Esperança, espiritualidade, objetivos distantes, corpo d'água. Indica fé no que está longe — sonho, meta de longo prazo, viagem além-mar. Pode virar alegria plena se a carta 26 estiver próxima." },
    }
};
DECKS.registrar(kipper);
